MTBS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include your app's URLs or any other URLs here
    path('', include('app.urls')),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/',home,name="home"),
    path('search/',search,name="search"),
    path('city_search/',city_search,name="city_search"),
    path('all_city_data',all_city_data,name="all_city_data"),
    path('admindash',admindash,name="admindash"),
    path('create_movie_page',create_movie_page,name="create_movie_page"),
    path('create_movie',create_movie,name="create_movie"),
    path('update_movie',update_movie,name="update_movie")
]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from cities_light.models import Country, City
# Create your models here.
class Address(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.country}, {self.city}"




class Language(models.Model):
    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(_("Title"), max_length=255)
    release_date = models.DateField(_("Release Date"))
    director = models.CharField(_("Director"), max_length=255)
    description = models.TextField(_("Description"))
    poster = models.ImageField(_("Poster"), upload_to='movie_posters/', null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Language"))

    def __str__(self):
        return self.title
   


# class Theater(models.Model):
#     name = models.CharField(_("Name"), max_length=255)
#     location = models.CharField(_("Location"), max_length=255)
#     capacity = models.PositiveIntegerField(_("Capacity"))
#     description = models.TextField(_("Description"))
#     photo = models.ImageField(_("Photo"), upload_to='theater_photos/', null=True, blank=True)
#     city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name=_("City"))

#     def __str__(self):
#         return self.name
    

# class Showtime(models.Model):
#     theater = models.ForeignKey(Theater, on_delete=models.CASCADE, verbose_name=_("Theater"))
#     movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name=_("Movie"))
#     start_time = models.DateTimeField(_("Start Time"))
#     end_time = models.DateTimeField(_("End Time"))
#     ticket_price = models.DecimalField(_("Ticket Price"), max_digits=8, decimal_places=2)

#     def __str__(self):
#         return f"{self.movie} at {self.theater} - {self.start_time}"

# class Booking(models.Model):
#     showtime = models.ForeignKey(Showtime, on_delete=models.CASCADE, verbose_name=_("Showtime"))
#     customer_name = models.CharField(_("Customer Name"), max_length=255)
#     customer_email = models.EmailField(_("Customer Email"))
#     booked_seats = models.PositiveIntegerField(_("Booked Seats"))
#     booking_date = models.DateTimeField(_("Booking Date"), auto_now_add=True)

#     def __str__(self):
#         return f"{self.customer_name} - {self.showtime} - Seats: {self.booked_seats}"
    
# class Ticket(models.Model):
#     showtime = models.ForeignKey(Showtime, on_delete=models.CASCADE, verbose_name=_("Showtime"))
#     seat_number = models.CharField(_("Seat Number"), max_length=10)
#     price = models.DecimalField(_("Price"), max_digits=8, decimal_places=2)
#     is_booked = models.BooleanField(_("Is Booked"), default=False)

#     def __str__(self):
#         return f"Ticket for {self.showtime} - Seat: {self.seat_number}" 

app/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from cities_light.models import City, Country
from .models import *
from datetime import datetime

def home(req):
    return render(req,'app/navbaar/home.html')

def search(request):
    return render(request,'app/search/search.html')

def city_search(request):
    query = request.GET.get('q', '')

    try: 
        india = Country.objects.get(pk=105)
        # Filter cities by name and country (India), case-insensitive
        cities = City.objects.filter(slug=query, country=india)
    except Country.DoesNotExist:
        raise Http404("Country 'India' not found in the database.")
    except Exception as e:
        # Handle other exceptions if needed
        print(f"An error occurred: {e}")
        raise Http404("An error occurred while processing the request.")

    print(cities) 
    return render(request, 'app/navbaar/home.html', {'cities': cities, 'query': query})

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def all_city_data(request):
    india = Country.objects.get(name='India')
    cities = City.objects.filter(country=india)

    # Paginate the cities with 40 cities per page
    paginator = Paginator(cities, 40)
    page = request.GET.get('page', 1)

    try:
        cities = paginator.page(page)
    except PageNotAnInteger:
        cities = paginator.page(1)
    except EmptyPage:
        cities = paginator.page(paginator.num_pages)

    return render(request, 'app/search/search.html', {'cities': cities})


def admindash(requset):
    return render(requset,'app/Admin_content/admindash.html')

def create_movie_page(request):
    if request.method == 'GET':
        return render(request,'app/Admin_content/curd/add_movie.html')

def create_movie(request):
    languages = Language.objects.all()
    if request.method == 'POST':
        title = request.POST['title']
        release_date = datetime.strptime(request.POST['release_date'], "%Y-%m-%d").date()
        director = request.POST['director']
        description = request.POST['description']
        poster = request.FILES['poster'] if 'poster' in request.FILES else None
        language_id = request.POST.get('language')

        
        new_movie = Movie.objects.create(
            title=title,
            release_date=release_date,
            director=director,
            description=description,
            poster=poster,
            language_id=language_id
        )

        return render(request, 'app/Admin_content/list_movie.html')

    
    
    return render(request, 'app/Admin_content/list_movie.html', {'languages': languages,'movie_data':new_movie})


     
def update_movie(request):
    
    movie=Movie.objects.all()
    return render(request,'app/Admin_content/curd/update_movie.html',{'movie':movie})




























# def movies(requset):
#     if requset.method=='GET':
       

#        movies=Movie.objects.all()

     

app/templates/app/Admin_content/admindash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> Admin Dashboard</title>
        <link href="{% static 'admin/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Admin</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="index.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Movie list
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Today Movie</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Weekly Movie</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Movie Controls
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Movie Curd
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="/create_movie_page">Add Movie</a>
                                            <a class="nav-link" href="/update_movie">Update Movie</a>
                                            <a class="nav-link" href="#">Delete Movie</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                      Cinemas
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">details</a>
                                            <a class="nav-link" href="404.html">showtimes</a>
                                            <a class="nav-link" href="500.html">seating </a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                      Bookings
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">day Bookings</a>
                                            <a class="nav-link" href="404.html">Monthly Bookingse</a>
                                            <a class="nav-link" href="500.html">Yearly Bookings</a>
                                        </nav>
                                    </div>
                                    
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Admin Data Oprations</h1>
                        <ol class="breadcrumb mb-4">
                            {% comment %} <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Sidenav Light</li> {% endcomment %}
                        </ol>
                        <div class="card mb-4">
                           {% block adminDashboard %}
                           
                           
                           
                           
                           {% endblock adminDashboard %}
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
       
<script src="{% static 'admin/js/scripts.js' %}"></script>
<script src="{% static 'admin/js/datatables-simple-demo.js' %}"></script>

    </body>
</html>

app/templates/app/Admin_content/curd/add_movie.html
{% extends "app/Admin_content/admindash.html" %}


{% block adminDashboard %}


<form action="{% url 'create_movie' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_title">Title</label>
            <input type="text" name="title" class="form-control" id="id_title" placeholder="Title">
        </div>
        <div class="form-group col-md-6">
            <label for="id_release_date">Release Date</label>
            <input type="date" name="release_date" class="form-control" id="id_release_date">
        </div>
    </div>
    
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_director">Director</label>
            <input type="text" name="director" class="form-control" id="id_director" placeholder="Director">
        </div>
        <div class="form-group col-md-6">
            <label for="id_description">Description</label>
            <textarea name="description" class="form-control" id="id_description" rows="3"></textarea>
        </div>
    </div>
    
    <div class="form-group">
        <label for="id_poster">Poster</label>
        <input type="file" name="poster" class="form-control-file" id="id_poster">
    </div>
    <div class="form-group">
        <label for="id_poster">Language</label>
        <input type="text" name="language" class="form-control-file" id="id_poster">
    </div>
    
    <!-- Add language field if needed -->
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



{% endblock adminDashboard %}

app/templates/app/Admin_content/curd/update_movie.html
{% extends "app/Admin_content/admindash.html" %}
{% block adminDashboard %}

<table class="table table-hover">
    <thead>
        <tr>
          <th scope="col">Poster</th>
          <th scope="col">Title</th>
          <th scope="col">Release Date</th>
          <th scope="col">Director</th>
          <th scope="col">Description</th>
          <th scope="col">Language</th>
          <th scope="col">Update</th>
        </tr>
    </thead>
    <tbody>
        {% for movie_instance in movie %}
        <tr>
          <td><img class="card-img" src="{{ movie_instance.poster.url }}" width="150px" height="150px" alt="{{ movie_instance.title }} Poster"></td>
          <td><h5 class="card-title">{{ movie_instance.title }}</h5></td>
          <td><p class="card-text">{{ movie_instance.release_date }}</p></td>
          <td><a href="#" class="btn btn-primary">{{ movie_instance.director }}</a></td>
          <td>{{ movie_instance.description }}</td>
          <td>{{ movie_instance.language.name }}</td>
          <td>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateModal{{ movie_instance.id }}">
                Update
            </button>
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock adminDashboard %}

app/templates/app/Get_in_tuch/review.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'get_in_tuch/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'get_in_tuch/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'get_in_tuch/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'get_in_tuch/css/style.css' %}">
    

    <title>Sidebar #3</title>
  </head>
  <body>
  
    
    <aside class="sidebar">
      <div class="toggle">
        <a href="#" class="js-menu-toggle menu-toggle">
          <span class="icon-mode_comment text-black"></span>
        </a>
      </div>
      <div class="side-inner">

        <div class="share">
          <h2>Get in touch</h2>
          <form action="#">
            <input type="text" class="form-control " placeholder="Enter your name">
            <input type="email" class="form-control " placeholder="Enter your email">
            <textarea class="form-control" name="" id="" cols="30" rows="5" placeholder="Write your message"></textarea>
            <input type="submit" class="btn btn-primary btn-block" value="Send">
          </form>
        </div>
        
      </div>
      
    </aside>


    <main>
      <div class="site-section">
        <div class="container">
          <div class="row justify-content-center">





            <div class="col-md-9">
              <div class="row">
                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_1.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_2.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_3.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_4.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_1.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_2.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_3.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="d-flex post-entry">
                    <div class="custom-thumbnail">
                      <img src="images/person_4.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="post-content">
                      <h3>How the gut microbes you're born with affect your lifelong health</h3>
                      <div class="post-meta"><span>Posted:</span> Dec 17, 2019</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>  
    </main>
    

    <script src="{% static 'get_in_tuch/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'get_in_tuch/js/popper.min.js' %}"></script>
    <script src="{% static 'get_in_tuch/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'get_in_tuch/js/main.js' %}"></script>
  </body>
</html>

app/templates/app/User_content/userdashbord.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Sidebar 04</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		{% load static %}
        <link rel="stylesheet" href="{% static 'user_content/css/style.css' %}">

  </head>
  <body>
		
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar" class="order-last" class="img" style="background-image: url(images/bg_1.jpg);">
				<div class="custom-menu">
					<button type="button" id="sidebarCollapse" class="btn btn-primary">
	        </button>
        </div>
        <div class="">
		  		<h1><a href="index.html" class="logo">Kenitic <span>Blog Agency</span></a></h1>
	        <ul class="list-unstyled components mb-5">
	          <li class="active">
	            <a href="#"><span class="fa fa-home mr-3"></span> Home</a>
	          </li>
	          <li>
	              <a href="#"><span class="fa fa-user mr-3"></span> About</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-sticky-note mr-3"></span> Blog</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-cogs mr-3"></span> Services</a>
	          </li>
	          <li>
              <a href="#"><span class="fa fa-paper-plane mr-3"></span> Contacts</a>
	          </li>
	        </ul>

	        <div class="mb-5 px-4">
						<h3 class="h6 mb-3">Subscribe for newsletter</h3>
						<form action="#" class="subscribe-form">
	            <div class="form-group d-flex">
	            	<div class="icon"><span class="icon-paper-plane"></span></div>
	              <input type="text" class="form-control" placeholder="Enter Email Address">
	            </div>
	          </form>
					</div>

	        <div class="footer px-4">
	        	<p>
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
						</p>
	        </div>

	      </div>

    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5 pt-5">
        <h2 class="mb-4">Sidebar #04</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
		</div>

		
		<script src="{% static 'user_content/js/jquery.min.js' %}"></script>
		<script src="{% static 'user_content/js/popper.js' %}"></script>
		<script src="{% static 'user_content/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'user_content/js/main.js' %}"></script>
		
  </body>
</html>

app/templates/app/movie_content/movie.html
{% extends "app/navbaar/base.html" %}
{% block container %}
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
{% endblock container %}